[mcp_servers.supabase]
command = "npx"
args = [
    "-y",
    "@supabase/mcp-server-supabase@latest",
    "--project-ref=vfxvcmympnugluqfqgks",
]

[mcp_servers.supabase.env]
SUPABASE_ACCESS_TOKEN = "YOUR_SUPABASE_TOKEN_HERE"
